config/routes.rb
Rails.application.routes.draw do
  # devise_for :admins
  # devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_for :users, controllers: {
    sessions:      'user/sessions',
    passwords:     'user/passwords',
    registrations: 'user/registrations'
  }

  devise_for :admin, controllers: {
    sessions:       'admin/sessions',
    passwords:      'admin/passwords',
    # registrations:  'admin/registrations'
  }

  scope module: :user do
    root :to => 'homes#top'
    get "/homes/about" =>"homes#about"
    resources :registrations, only:[:new, :create]
    get "mypage", to: "mypages#mypage"
    get "/mypages/edit", to: "mypages#edit"
    patch "/mypages/edit", to: "mypages#update"
    get "mypages", to: "mypages#show"
    resources :reviews, only:[:show, :new, :create, :update, :destroy]
    resources :comments, only:[:create, :destroy]
    resources :movies, only:[:show] do
      collection do
        get "/search", to: 'movies#search'
      end
    end
    resources :users, only:[:show]
  end

  namespace :admin do
    root :to => 'homes#top'
    resources :movies, only:[:new, :create, :edit, :update, :destroy] do
      collection do
        get "/search", to: 'movies#search'
      end
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :reviews, dependent: :destroy
  has_many :comments, dependent: :destroy

   validates :nickname, presence: true
   validates :email, presence: true
end

app/controllers/user/comments_controller.rb
class User::CommentsController < ApplicationController

  def create
    comment = Comment.new(comment_params)
    comment.user_id = current_user.id
    comment.save
    redirect_to review_path(comment.review_id)
    # if comment.save
    #   redirect_to review_path(comment.review_id)
    # else
    #   render template: "user/reviews/show"
    # end
  end

  def destroy
    comment = Comment.find(params[:id])
    comment.user_id = current_user.id
    comment.destroy
    redirect_to review_path(comment.review_id)
  end

  private
  def review_params
    params.require(:review).permit(:movie_id, :comment_id, :score, :content)
  end

  def comment_params
    params.require(:comment).permit(:content, :user_id, :review_id)
  end

  def user_params
    params.require(:user).permit(:nickname)
  end
end

app/controllers/user/homes_controller.rb
class User::HomesController < ApplicationController
  def top
    @movies = Movie.page(params[:page]).per(6)
  end

  def about
  end
end

app/controllers/user/movies_controller.rb
class User::MoviesController < ApplicationController

   def show
     @movie = Movie.find(params[:id])
     @reviews = @movie.reviews
   end

   def search
    method = params[:search_method]
    word = params[:search_word]
    @movies = Movie.search(method,word)
   end
end

app/controllers/user/mypages_controller.rb
class User::MypagesController < ApplicationController
  def mypage
  end

  def show
    @user = current_user
    @reviews = @user.reviews
  end

  def edit
    @user = current_user
  end

  def update
    user = current_user
    user.update(user_params)
    redirect_to mypage_path(current_user)
  end

  private
  def review_params
    params.require(:review).permit(:movie_id, :comment_id, :score, :content)
  end

  def movie_params
    params.require(:movie).permit(:review_id, :title, :image, :introduction, :created_year, :director, :cast, :genre_id)
  end

  def user_params
    params.require(:user).permit(:nickname, :email)
  end
end

app/controllers/user/passwords_controller.rb
# frozen_string_literal: true

class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/registrations_controller.rb
# frozen_string_literal: true

class User::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/reviews_controller.rb
class User::ReviewsController < ApplicationController
  before_action :move_to_signed_in

  # before_action :authenticate_user, {only: [:show, :new, :create, :destroy]}
  # index: findメソッドは使えない
  # show: allメソッド使える
  def show
    @review = Review.find(params[:id])
    @comments = @review.comments
    @comment_new = Comment.new
  end

  def new
    @review = Review.new
    @movie = Movie.find(params[:movie_id])
  end

  def create
    @review = Review.new(review_params)
    @movie =  Movie.find(review_params[:movie_id])
    @review.user_id = current_user.id
    if @review.save
      redirect_to movie_path(@movie)
    else
      render "new"
    end
  end

  def destroy
    review = Review.find(params[:id])
    # pp review
    review.destroy!
    redirect_to mypages_path
  end

  private
  def movie_params
    params.require(:movie).permit(:title, :image, :introduction, :created_year, :director, :cast, :genre_id, :review_id)
  end

  def review_params
    params.require(:review).permit(:movie_id, :comment_id, :score, :content)
  end

  def user_params
    params.require(:user).permit(:nickname)
  end

  def move_to_signed_in
    unless user_signed_in?
      #サインインしていないユーザーはログインページが表示される
      redirect_to  '/users/sign_in'
    end
  end
end

app/controllers/user/sessions_controller.rb
# frozen_string_literal: true

class User::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/user/users_controller.rb
class User::UsersController < ApplicationController
  def show
   @review = Review.find(params[:id])
   @user = @review.user
   @reviews = @user.reviews
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/helpers/user/comments_helper.rb
module User::CommentsHelper
end

app/helpers/user/homes_helper.rb
module User::HomesHelper
end

app/helpers/user/mypages_helper.rb
module User::MypagesHelper
end

app/helpers/user/reviews_helper.rb
module User::ReviewsHelper
end

app/views/user/reviews/new.html.erb
<%# if @review.errors.any? %>
  <!--<%#= @review.errors.count %>件のエラーが発生しました-->
  <%# @review.errors.full_messages.each do |message| %>
    <%#= message %>
  <%# end %>
<%# end %>


<%= form_with model: @review, local: true do |f| %>
<%= render 'layouts/error_messages', model: f.object%>
  <%= f.hidden_field :movie_id, value: @movie.id %>
  <%= current_user.nickname %>
  <div class="field" id="star">
  <%= f.label :score, "星評価：" %>
  <%= f.hidden_field :score, id: :review_star %>
  <script>
    $('#star').raty({
      size     : 36,
      starOff:  '<%= asset_path('star-off.png') %>',
      starOn : '<%= asset_path('star-on.png') %>',
      starHalf: '<%= asset_path('star-half.png') %>',
      scoreName: 'review[score]',
      half: true,
    });
  </script>
</div>
<%= f.label :content, "レビュー" %>
<%= f.text_area :content  %>
<%= f.submit "投稿する" %>
<% end %>

app/views/user/reviews/show.html.erb
<h5>
  <%= @review.user.nickname %>
  <%= link_to "投稿レビューをすべて見る", user_path(@review), class: "btn btn-success" %>
</h5>
<div class="review">
   <div class="relative-post-evaluation">
          <%= @review.user.nickname %><br>
          <%= @review.content %><br>
          <%= link_to movie_path(@review.movie) do %>
            <div class="movies_show_link">
              <%= attachment_image_tag @review.movie, :image, :fill, 50, 50, format: 'jpeg' %>
              <%= @review.movie.title %>
              <%= @review.movie.created_year %>,
              <%= @review.movie.genre_id %>
              <span id="star-rate-<%= @review.id %>"></span>
              <script>
              $('#star-rate-<%= @review.id %>').empty();
                $('#star-rate-<%= @review.id %>').raty({
                  size: 36,
                  starOff: "<%= asset_path('star-off.png') %>",
                  starOn: "<%= asset_path('star-on.png') %>",
                  starHalf: "<%= asset_path('star-half.png') %>",
                  half: true,
                  readOnly: true,
                  score: <%= @review.score %>,
                });
              </script><br>
            </div>
          <% end %>
        </div>
      </div>

<h4>コメント一覧</h4>
<% @comments.each do |comment| %>
<div class="comments">
  <%= comment.user.nickname %>
  <%= comment.created_at.strftime("%Y年%m月%d日 %H:%M:%S") %><br>
  <%= comment.content %><br>
  <% if user_signed_in? && current_user.id == comment.user_id %>
    <%= link_to "削除", comment_path(comment), method: :delete, class: "btn btn-danger" %>
  <% end %>
</div>
<% end %>

<h4>コメントする</h4>
<div class="content">
  投稿者：<%= current_user.nickname %>
  <%= form_with model: @comment_new, url: "/comments", local:true do |f| %>
  <!--<%#= render 'layouts/error_messages', model: f.object%>効かない-->
    <div class="field">
      <%= f.label :コメント %><br>
      <%= f.text_area :content, size: "50x8" %>
      <%= f.hidden_field :review_id, :value => @review.id %>
    </div>

    <div class="action">
      <%= f.submit "送信" %>
    </div>
  <% end %>
</div>