config/routes.rb
Rails.application.routes.draw do
  # devise_for :admins
  # devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_for :users, controllers: {
    sessions:      'user/sessions',
    passwords:     'user/passwords',
    registrations: 'user/registrations'
  }

  devise_for :admin, controllers: {
    sessions:       'admin/sessions',
    passwords:      'admin/passwords',
    # registrations:  'admin/registrations'
  }

  scope module: :user do
    root :to => 'homes#top'
    get "/homes/about" =>"homes#about"
    resources :registrations, only:[:new, :create]
    get "mypage", to: "mypages#mypage"
    get "/mypages/edit", to: "mypages#edit"
    patch "/mypages/edit", to: "mypages#update"
    get "mypages", to: "mypages#show"
    resources :reviews, only:[:show, :new, :create, :update, :destroy]
    resources :comments, only:[:create, :destroy]
    resources :movies, only:[:show] do
      collection do
        get "/search", to: 'movies#search'
      end
    end
    resources :users, only:[:show]
  end

  namespace :admin do
    root :to => 'homes#top'
    resources :movies, only:[:new, :create, :edit, :update, :destroy] do
      collection do
        get "/search", to: 'movies#search'
      end
    end
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, #:registerable　←新規登録画面が作られない
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :review
  belongs_to :user

   validates :content, presence: true
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :movies, dependent: :destroy

  validates :name, presence: true

end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :reviews, dependent: :destroy
  belongs_to :genre
  attachment :image
  # enum genre_id: { action: 0, comedy: 1, horror: 2, mystery: 3, romance: 4, sf: 5 }

  validates :title, presence: true
  # validates :image_id, presence: true
  validates :created_year, presence: true
  validates :director, presence: true
  validates :cast, presence: true
  validates :introduction, presence: true

  def self.search(method,word)#なぜか引数methodを入れると上手くいく
    # if method == "forward_match"
    #         @movies = Movie.where(["title LIKE ? OR created_year LIKE ? OR introduction LIKE ? OR director LIKE ? OR `cast` LIKE ?","#{word}%","#{word}%","#{word}%","#{word}%","#{word}%"])
    # elsif method == "backward_match"
    #         @movies = Movie.where(["title LIKE ? OR created_year LIKE ? OR introduction LIKE ? OR director LIKE ? OR `cast` LIKE ?","%#{word}","%#{word}","%#{word}","%#{word}","%#{word}"])
    # elsif method == "perfect_match"
    #         @movies = Movie.where(["title LIKE ? OR created_year LIKE ? OR introduction LIKE ? OR director LIKE ? OR `cast` LIKE ?","#{word}","#{word}","#{word}","#{word}","#{word}"])
    # if method == "partial_match"
            @movies = Movie.where(["title LIKE ? OR created_year LIKE ? OR introduction LIKE ? OR director LIKE ? OR `cast` LIKE ?","%#{word}%","%#{word}%","%#{word}%","%#{word}%","%#{word}%"])
    # else
            # @movies = Movie.all
    # end
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :movie
  has_many :comments, dependent: :destroy

   validates :score, presence: true
   validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :reviews, dependent: :destroy
  has_many :comments, dependent: :destroy

   validates :nickname, presence: true
   validates :email, presence: true
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @movies = Movie.all
  end
end

app/controllers/admin/movies_controller.rb
class Admin::MoviesController < ApplicationController
  def new
    @movie = Movie.new
    @movie.genre
  end

  def create
    @movie = Movie.new(movie_params)
    if @movie.save
      redirect_to admin_root_path
    else
      render :new
    end
  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def update
    movie = Movie.find(params[:id])
    movie.update(movie_params)
    redirect_to admin_root_path
  end

  def destroy
    movie = Movie.find(params[:id])
    movie.destroy
    redirect_to admin_root_path
  end

   def search
    method = params[:search_method]#なぜか変数methodを入れると上手くいく
    word = params[:search_word]
    @movies = Movie.search(method,word)#←ここも
   end

  private
  def movie_params
    params.require(:movie).permit(:review_id, :genre_id, :title, :image, :introduction, :created_year, :director, :cast)
  end
  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  # def authenticate_user
  #   if @current_user==nil
  #     flash[:notice]="ログインが必要です"
  #     redirect_to("/users/sign_in")
  #   end
  # end



def after_sign_in_path_for(resource_or_scope)
    if resource_or_scope.is_a?(Admin)
        admin_root_path
    else
        mypage_path
    end
end


  def after_sign_out_path_for(resource_or_scope)
    if resource_or_scope == :admin
      new_admin_session_path
    else
      root_path
    end
  end


  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/user/homes_controller.rb
class User::HomesController < ApplicationController
  def top
    @movies = Movie.page(params[:page]).per(6)
  end

  def about
  end
end

app/controllers/user/movies_controller.rb
class User::MoviesController < ApplicationController

   def show
     @movie = Movie.find(params[:id])
     @reviews = @movie.reviews
   end

   def search
    method = params[:search_method]
    word = params[:search_word]
    @movies = Movie.search(method,word)
   end
end

app/controllers/user/users_controller.rb
class User::UsersController < ApplicationController
  def show
   @review = Review.find(params[:id])
   @user = @review.user
   @reviews = @user.reviews
  end
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/movies_helper.rb
module Admin::MoviesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user/comments_helper.rb
module User::CommentsHelper
end

app/helpers/user/homes_helper.rb
module User::HomesHelper
end

app/helpers/user/mypages_helper.rb
module User::MypagesHelper
end

app/helpers/user/reviews_helper.rb
module User::ReviewsHelper
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<!--model:操作対象。エラーメッセージを一つづつ取り出し、message変数に入れて出力する-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MovieMaps</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/91078cb5ad.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  </head>

  <body>
    <header>
      <nav class="navbar navbar-light navbar-expand-lg">
        <div class="container">

            <div class="navbar-brand">
              <%= link_to "Movie Maps", root_path, class: "link-logo" %>
            </div>

            <!--<%# if customer_signed_in? %>-->
            <!--  ようこそ、<%#= current_customer.last_name %>さん！-->
            <!--<%# end %>-->


            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
              <% if admin_signed_in? %>
                <li class="nav-item active"><%= link_to "Home", root_path, class: "link"  %></li>
                <li class="nav-item active"><%= link_to "映画一覧表", admin_root_path, class: "link" %></li>
                <li class="nav-item active"><%= link_to "映画登録", new_admin_movie_path, class: "link" %></li>
                <li class="nav-item active"><%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "link" %></li>
              <% elsif user_signed_in? %>
                <li class="nav-item active"><%= link_to 'About', homes_about_path, class: "link" %></li>
                <li class="nav-item active"><%= link_to "Home", root_path, class: "link"  %></li>
                <li class="nav-item active"><%= link_to "マイページ", mypage_path, class: "link"  %></li>
                <li class="nav-item active"><%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "link" %></li>
               <% else %>
                <li class="nav-item active"><%= link_to "About", homes_about_path, class: "link" %></li>
                <li class="nav-item active"><%= link_to "Home", root_path, class: "link"  %></li>
                <li class="nav-item active"><%= link_to "新規登録", new_user_registration_path, class: "link"  %></li>
                <li class="nav-item active"><%= link_to "ログイン", new_user_session_path, class: "link"  %></li>
              <% end %>
            </ul>
            </div>
          </div>
        </nav>
      </div>

      <div class="search_field">
        <% if admin_signed_in? %>
          <%= form_tag(search_admin_movies_path, method: :get) do %>
            <%#= select(@search_content, :search_method, [["前方一致","forward_match"], ["後方一致","backward_match"], ["完全一致","perfect_match"], ["部分一致","partial_match"]])%>
            <%= text_field(@search_content, :search_word, placeholder: "\uf002", class: "fa")%>
            <%= submit_tag "検索" %>
          <% end %>
        <% elsif %>
          <%= form_tag(search_movies_path, method: :get) do %>
            <%#= select(@search_content, :search_method, [["前方一致","forward_match"], ["後方一致","backward_match"], ["完全一致","perfect_match"],["部分一致","partial_match"]])%>
            <%= text_field(@search_content, :search_word, placeholder: "\uf002", class: "fa")%>
            <%= submit_tag "検索" %>
          <% end %>
        <% end %>
      </div>
    </header>

    <main>
      <%= yield %>
    </main>
  </body>
</html>